apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-yy83
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0049-tenant/tkrw-pr712-0075-0049-app/devfile-sample-yy83@sha256:21cddc7d53aadef7abed0d2fb96b832044952c74e44052a7a766aed02764e23b
        name: my-nodejs
        resources: {}
status: {}
